/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternationalIndexRouteImport } from './routes/international/index'
import { Route as HajjAndUmrahIndexRouteImport } from './routes/hajj-and-umrah/index'
import { Route as DomesticIndexRouteImport } from './routes/domestic/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalIndexRoute = InternationalIndexRouteImport.update({
  id: '/international/',
  path: '/international/',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjAndUmrahIndexRoute = HajjAndUmrahIndexRouteImport.update({
  id: '/hajj-and-umrah/',
  path: '/hajj-and-umrah/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticIndexRoute = DomesticIndexRouteImport.update({
  id: '/domestic/',
  path: '/domestic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domestic/': typeof DomesticIndexRoute
  '/hajj-and-umrah/': typeof HajjAndUmrahIndexRoute
  '/international/': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domestic': typeof DomesticIndexRoute
  '/hajj-and-umrah': typeof HajjAndUmrahIndexRoute
  '/international': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domestic/': typeof DomesticIndexRoute
  '/hajj-and-umrah/': typeof HajjAndUmrahIndexRoute
  '/international/': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domestic/'
    | '/hajj-and-umrah/'
    | '/international/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/domestic' | '/hajj-and-umrah' | '/international' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/domestic/'
    | '/hajj-and-umrah/'
    | '/international/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomesticIndexRoute: typeof DomesticIndexRoute
  HajjAndUmrahIndexRoute: typeof HajjAndUmrahIndexRoute
  InternationalIndexRoute: typeof InternationalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international/': {
      id: '/international/'
      path: '/international'
      fullPath: '/international/'
      preLoaderRoute: typeof InternationalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-and-umrah/': {
      id: '/hajj-and-umrah/'
      path: '/hajj-and-umrah'
      fullPath: '/hajj-and-umrah/'
      preLoaderRoute: typeof HajjAndUmrahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic/': {
      id: '/domestic/'
      path: '/domestic'
      fullPath: '/domestic/'
      preLoaderRoute: typeof DomesticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomesticIndexRoute: DomesticIndexRoute,
  HajjAndUmrahIndexRoute: HajjAndUmrahIndexRoute,
  InternationalIndexRoute: InternationalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
